Vagrant.configure("2") do |config|
  config.vm.box = "Sliim/kali-linux-2.0-amd64"

  config.vm.network "public_network"
  config.ssh.username = "root"
  config.ssh.private_key_path = "./insecure_private_key"
  config.vm.network :public_network, ip: "192.168.1.201"
  config.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
  end
end
